---
- name: Install MySQL-Client
  apt: name=mariadb-client update_cache=yes cache_valid_time=3600

- name: Get wpcli
  get_url:
          url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          dest=/root/wp-cli.phar
          timeout=60
  register: download_wpcli

- name: Setup wpcli
  copy:
          remote_src=true
          src=/root/wp-cli.phar
          dest=/usr/local/bin/wp
          owner=root
          group=root
          mode=0755
  register: setup_wpcli

- name: Download wp core
  shell: wp core download --allow-root --locale=ja --path="/var/www/html"
  register: download_wp
  failed_when: download_wp.rc not in [0, 1]

- name: Change Owner / Group
  file:
          path=/var/www/html
          recurse=yes
          owner=www-data
          group=www-data

- name: Generate wp config 
  shell: wp core config --allow-root --dbname="wordpress" --dbuser="wpuser" --dbpass="password" --dbhost="raspnetes02.local" --path="/var/www/html"
  register: generate_wpconfig
  failed_when: generate_wpconfig.rc not in [0, 1]

- name: Install Wordpress
  shell: wp core install --allow-root --url="http://raspnetes01.local/" --title="TestSite" --admin_user="admin" --admin_password="password" --admin_email="abc@example.com" --path="/var/www/html"
  register: install_wordpress
  failed_when: install_wordpress.rc not in [0, 1]

- name: Delete Index HTML
  file:
          path=/var/www/html/index.html
          state=absent
