---
- name: Install MySQL-Client
  apt: name=mariadb-client update_cache=yes cache_valid_time=3600

- name: Get Wordpress Archive
  get_url:
          url=https://ja.wordpress.org/latest-ja.tar.gz
          dest=/var/www/html
          timeout=30
  register: download_tarfile

- name: Unarchive
  unarchive:
          src: "{{download_tarfile.dest}}"
          dest: /var/www/html
          remote_src: yes
