---
- name: Install Mysql-Server
  apt: name=mariadb-server update_cache=yes cache_valid_time=3600
- name: Install Mysql-Client
  apt: name=mariadb-client update_cache=yes cache_valid_time=3600
- name: Install Mysql-Python-Client
  pip:
          name: PyMySQL
- name: Start Mysql
  service: name=mysql state=started enabled=yes
