---
- name : Create Wordpress User
  command: mysql --user root --execute="CREATE USER 'wpuser'@'localhost' IDENTIFIED BY '{{mysql.user_password}}';"
  register: create_dbuser
  failed_when: create_dbuser.rc not in [0, 1]

- name : Grant Wordpress User
  command: mysql --user root --execute="GRANT ALL ON *.* TO 'wpuser'@'localhost';"
  register: grant_dbuser
  failed_when: grant_dbuser.rc not in [0, 1]

- name: Create JDBC File
  template:
          src: .my.cnf.j2
          dest: "{{ mysql.defaults_file }}"
          owner: root
          group: root
          mode: 0600

- name: Create wordpress DB
  mysql_db:
          name: wordpress
          state: present
