---
- name: Install PHP
  apt: name=php7.2 update_cache=yes cache_valid_time=3600
- name: Install PHP-mysql(7.2)
  apt: name=php7.2-mysql update_cache=yes cache_valid_time=3600
- name: Restart Apache Service
  service: name=apache2 state=restarted
